language: cpp
sudo: require
dist: trusty

os:
 - linux
 - osx
matrix:
 exclude:
# Don't build with clang on Linux
  - os: linux
    compiler: clang
# Don't build with gcc on OSX
  - os: osx
    compiler: gcc

before_install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo add-apt-repository ppa:beineri/opt-qt487-trusty;
    sudo apt update && sudo apt install opt-qt4-dev-tools;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
    brew update > /dev/null; 
    brew install qt4;
    chmod -R 755 /usr/local/opt/qt4/*;
    export QTDIR="/usr/local/opt/qt4";
    export PATH="$QTDIR/bin:$PATH";
  fi
script:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
    source /opt/qt*/bin/qt*-env.sh; 
    qmake test.pro; 
    make;
    sudo make install; 
    make DESTDIR=appdir/ install; find appdir/; 
    rm -rf appdir/usr/include appdir/usr/mkspecs appdir/usr/lib/x86_64-linux-gnu/; 
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"; 
    chmod a+x linuxdeployqt*.AppImage; 
    unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH; 
    ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs; 
    ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage; 
  fi
- # if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
    cmake -DBUILD_GUI=ON CMakeLists.txt; 
    make;
    mkdir testclient/atcore-gui.app/Contents/MacOS/plugins; 
    mv src/plugins/*.dylib testclient/atcore-gui.app/Contents/MacOS/plugins/; 
    macdeployqt testclient/atcore-gui.app/ -dmg; 
  fi
after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
    find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq; 
    bash ./upload.sh ./AtCore*.AppImage*;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then bash ./upload.sh testclient/atcore-gui*.dmg*; fi 
 
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - # /^(?i:continuous)$/