sudo: false
language: cpp

env:
  global:
    - BIN=browser
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++"

  exclude:
  - os: linux
    compiler: clang

before_install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then  
    sudo add-apt-repository ppa:beineri/opt-qt487-trusty -y;
    sudo apt update -qq; sudo apt install opt-qt4-dev-tools -y;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update > /dev/null;
    brew tap cartr/qt4
    brew tap-pin cartr/qt4
    brew install qt@4
    chmod -R 755 /usr/local/opt/qt4/*;
    export QTDIR="/usr/local/opt/qt4";
    export PATH="$QTDIR/bin:$PATH";
    export ARTIFACT="$BIN*.dmg";
  fi

script:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
    source /opt/qt*/bin/qt*-env.sh;
    qmake DESTDIR=deploy test.pro;
    make; 
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
    ./linuxdeployqt*.AppImage deploy/$BIN -verbose=2 -bundle-non-qt-libs -appimage;
    export ARTIFACT="$BIN"-x86_64.AppImage;
    mv Application-x86_64.AppImage $ARTIFACT;
    find . | grep AppImage;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    mkdir deploy;
    cd deploy;
    qmake ..;
    make;
    macdeployqt $BIN.app/ -dmg;
    find . | grep dmg;
  fi
after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh;
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
    find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq;
    bash ./upload.sh $ARTIFACT;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
    bash ./upload.sh $ARTIFACT;
  fi
branches:
  except:
    - /^(?i:continuous)$/
